"use client"

import {
  useEffect,
  useState,
} from "react"

import {
  AlertCircle,
  Bell,
  CheckCircle2,
  Clock,
  Info,
  Loader2,
} from "lucide-react"

import {
  getNotifications,
} from "@/lib/api"

import type {
  Notification,
} from "@/types"


function NotificationIcon({
  type,
}: {
  type: Notification["type"]
}) {
  switch (type) {
    case "success":
      return (
        <CheckCircle2 className="h-5 w-5 text-success" />
      )

    case "warning":
      return (
        <AlertCircle className="h-5 w-5 text-warning" />
      )

    case "error":
      return (
        <AlertCircle className="h-5 w-5 text-danger" />
      )

    default:
      return (
        <Info className="h-5 w-5 text-primary" />
      )
  }
}


export default function NotificationsPage() {
  const [
    notifications,
    setNotifications,
  ] = useState<Notification[]>([])

  const [
    isLoading,
    setIsLoading,
  ] = useState(true)

  const [
    error,
    setError,
  ] = useState<string | null>(null)


  useEffect(() => {
    async function loadNotifications(): Promise<void> {
      try {
        setIsLoading(true)
        setError(null)

        const data = await getNotifications()

        setNotifications(data)
      } catch (requestError) {
        console.error(
          "Failed to load recent updates",
          requestError,
        )

        setError(
          "Unable to load recent updates. Please try again.",
        )
      } finally {
        setIsLoading(false)
      }
    }

    void loadNotifications()
  }, [])


  return (
    <div className="mx-auto max-w-4xl pb-8">
      <div className="mb-8">
        <h1 className="text-2xl font-bold tracking-tight text-foreground">
          Recent Updates
        </h1>

        <p className="mt-1 text-muted-foreground">
          Activity generated by your tasks, approvals and documents.
        </p>
      </div>

      <div className="overflow-hidden rounded-2xl border border-border/60 bg-card shadow-sm">
        {isLoading ? (
          <div className="flex h-64 flex-col items-center justify-center space-y-4 text-muted-foreground">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />

            <p>Loading recent updates...</p>
          </div>
        ) : error ? (
          <div className="flex h-64 flex-col items-center justify-center gap-3 p-6 text-center">
            <AlertCircle className="h-8 w-8 text-danger" />

            <p className="text-sm font-medium text-danger">
              {error}
            </p>
          </div>
        ) : notifications.length === 0 ? (
          <div className="flex h-64 flex-col items-center justify-center p-6 text-center">
            <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-muted/50">
              <Bell className="h-8 w-8 text-muted-foreground opacity-40" />
            </div>

            <h3 className="mb-1 text-lg font-medium text-foreground">
              No recent updates
            </h3>

            <p className="text-sm text-muted-foreground">
              New task and document activity will appear here.
            </p>
          </div>
        ) : (
          <div className="divide-y divide-border/60">
            {notifications.map((notification) => (
              <article
                key={notification.notification_id}
                className="flex gap-4 p-4 sm:p-6"
              >
                <div className="mt-1 shrink-0">
                  <NotificationIcon
                    type={notification.type}
                  />
                </div>

                <div className="min-w-0 flex-1">
                  <div className="mb-1 flex items-start justify-between gap-4">
                    <h2 className="text-base font-medium text-foreground">
                      {notification.title}
                    </h2>

                    <span className="flex shrink-0 items-center gap-1 whitespace-nowrap text-xs text-muted-foreground">
                      <Clock className="h-3 w-3" />

                      {notification.timestamp}
                    </span>
                  </div>

                  <p className="text-sm leading-relaxed text-muted-foreground">
                    {notification.description}
                  </p>
                </div>
              </article>
            ))}
          </div>
        )}
      </div>

      <p className="mt-4 text-xs text-muted-foreground">
        These updates are generated from Clerkly&apos;s task audit history.
      </p>
    </div>
  )
}