"""add Stripe payment tracking

Revision ID: 2604956eeca7
Revises: 072baedec8db
Create Date: 2026-08-17 17:00:57.139179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2604956eeca7'
down_revision: Union[str, Sequence[str], None] = '072baedec8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.alter_column('payment_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_tasks_payment_intent_id'), ['payment_intent_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_payment_intent_id'))
        batch_op.alter_column('payment_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_intent_id')
        batch_op.drop_column('payment_provider')

    # ### end Alembic commands ###
