"""add gmail oauth fields to users

Revision ID: 4c055456d554
Revises: ed41bc65f540
Create Date: 2026-08-20 20:00:29.385881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c055456d554'
down_revision: Union[str, Sequence[str], None] = 'ed41bc65f540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail_connected', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('google_access_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_refresh_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_token_expiry', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_token_expiry')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_access_token')
        batch_op.drop_column('gmail_connected')

    # ### end Alembic commands ###
