"""add docusign fields to users and tasks

Revision ID: 549edc8909f6
Revises: 4c055456d554
Create Date: 2026-08-21 15:24:08.211554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549edc8909f6'
down_revision: Union[str, Sequence[str], None] = '4c055456d554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('signature_envelope_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('signature_status', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_signature_envelope_id'), ['signature_envelope_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docusign_connected', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('docusign_access_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('docusign_refresh_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('docusign_token_expiry', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('docusign_token_expiry')
        batch_op.drop_column('docusign_refresh_token')
        batch_op.drop_column('docusign_access_token')
        batch_op.drop_column('docusign_connected')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_signature_envelope_id'))
        batch_op.drop_column('signature_status')
        batch_op.drop_column('signature_envelope_id')
        batch_op.drop_column('signature_provider')

    # ### end Alembic commands ###
