"""add payment provider session

Revision ID: 726d591c5f2d
Revises: 2604956eeca7
Create Date: 2026-08-17 17:21:59.560769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726d591c5f2d'
down_revision: Union[str, Sequence[str], None] = '2604956eeca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_session_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_provider_session_id'), ['provider_session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_provider_session_id'))
        batch_op.drop_column('provider_session_id')

    # ### end Alembic commands ###
