"""add plan_reasoning and plan_source to tasks

Revision ID: ed41bc65f540
Revises: d2302178015e
Create Date: 2026-08-20 18:10:19.238758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed41bc65f540'
down_revision: Union[str, Sequence[str], None] = 'd2302178015e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_reasoning', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('plan_source', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('plan_source')
        batch_op.drop_column('plan_reasoning')

    # ### end Alembic commands ###
